name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  BUILD_STATIC: false

jobs:
  build:
    runs-on: ${{ matrix.sys.os }} 
    strategy:
      matrix:
        sys: 
          - { os: windows-latest, shell: pwsh }
          - { os: ubuntu-latest,  shell: 'alpine.sh --root {0}'  }
          - { os: macos-latest,   shell: bash  }
    defaults:
      run:
        shell: ${{ matrix.sys.shell }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    
    - name: Setup latest Alpine Linux
      uses: jirutka/setup-alpine@39d2d96fa8e4b713be89c0239a5c3b9a0f49838d
      if: ${{ matrix.sys.os == 'ubuntu-latest' }}
      with:
        arch: x86_64
        packages: >
          make
          cmake
          libstdc++
          g++
          musl-dev
      
    - name: Configure CMake
      env:
        BUILD_STATIC: ${{ matrix.sys.os == 'ubuntu-latest' }}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_STATIC=${{env.BUILD_STATIC}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
